version: "3.8"
services:
  web:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    volumes:
      - ./backend:/app   # 挂载 backend 文件夹
    ports:
      - "8000:80"
    environment:
      - MODULE_NAME=app.main    # 指定 FastAPI 的入口点 (backend/app/main.py)
      - VARIABLE_NAME=app       # FastAPI 实例的名称
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb

volumes:
  postgres_data:
